### ISSUE TITLE
Problem with timezones

### ISSUE THREAD

**Issue by raghibislam** [StreamFlow-Finance/streamflow-app#25]
UTC is being used in lot of places where local timezone should be used.
This leads to unexpected (and often plain wrong) behavior of the app

**Comment by imprfekt** [comment]
Thanks for reporting @raghibislam!
Can you provides steps to reproduce and/or a screen recording so we can troubleshoot this better?

**Comment by imprfekt** [comment]
@raghibislam?

**Comment by raghibislam** [comment]
@imprfekt change your time zone to san fransisco and try to run the app , you will get date error.

**Comment by imprfekt** [comment]
I see the problem. Will get to it soon. 
Thanks for reporting!
